// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using monchotradebackend.data;

#nullable disable

namespace monchotradeBackend.Data.Migrations.Sqlite
{
    [DbContext(typeof(MonchoDbContext))]
    [Migration("20241104192418_InitialSqlite")]
    partial class InitialSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("monchotradebackend.models.entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5665),
                            Description = "Classic blue jeans for everyday wear",
                            IsActive = true,
                            Name = "Men's Jeans",
                            Quantity = 10,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5669),
                            Description = "Comfortable cotton t-shirt, perfect for casual outings",
                            IsActive = true,
                            Name = "Casual T-Shirt",
                            Quantity = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5672),
                            Description = "Noise-cancelling headphones with high-quality sound",
                            IsActive = true,
                            Name = "Wireless Headphones",
                            Quantity = 8,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5714),
                            Description = "Portable speaker with long battery life",
                            IsActive = true,
                            Name = "Bluetooth Speaker",
                            Quantity = 12,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Category = "Footwear",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5724),
                            Description = "Comfortable and durable sports shoes",
                            IsActive = true,
                            Name = "Sports Sneakers",
                            Quantity = 7,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            Category = "Footwear",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5730),
                            Description = "Lightweight running shoes for everyday exercise",
                            IsActive = true,
                            Name = "Running Shoes",
                            Quantity = 10,
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5733),
                            Description = "Fast-charging USB-C charger",
                            IsActive = true,
                            Name = "Smartphone Charger",
                            Quantity = 15,
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5753),
                            Description = "10,000mAh power bank for mobile devices",
                            IsActive = true,
                            Name = "Power Bank",
                            Quantity = 9,
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5756),
                            Description = "Stylish white formal shirt, perfect for office",
                            IsActive = true,
                            Name = "Formal Shirt",
                            Quantity = 11,
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5759),
                            Description = "Comfortable black dress pants for formal events",
                            IsActive = true,
                            Name = "Dress Pants",
                            Quantity = 6,
                            UserId = 5
                        },
                        new
                        {
                            Id = 11,
                            Category = "Office Supplies",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5763),
                            Description = "Ergonomic stand for laptops",
                            IsActive = true,
                            Name = "Laptop Stand",
                            Quantity = 8,
                            UserId = 6
                        },
                        new
                        {
                            Id = 12,
                            Category = "Office Supplies",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5766),
                            Description = "Compact wireless mouse for convenience",
                            IsActive = true,
                            Name = "Wireless Mouse",
                            Quantity = 13,
                            UserId = 6
                        },
                        new
                        {
                            Id = 13,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5769),
                            Description = "Sporty digital watch with water resistance",
                            IsActive = true,
                            Name = "Digital Watch",
                            Quantity = 14,
                            UserId = 7
                        },
                        new
                        {
                            Id = 14,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5772),
                            Description = "Tracks steps, calories, and more",
                            IsActive = true,
                            Name = "Fitness Tracker",
                            Quantity = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 15,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5779),
                            Description = "Stylish and warm winter jacket",
                            IsActive = true,
                            Name = "Men's Jacket",
                            Quantity = 4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 16,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5817),
                            Description = "Soft wool scarf for cold weather",
                            IsActive = true,
                            Name = "Wool Scarf",
                            Quantity = 7,
                            UserId = 8
                        },
                        new
                        {
                            Id = 17,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5820),
                            Description = "10-inch tablet with high-resolution display",
                            IsActive = true,
                            Name = "Tablet",
                            Quantity = 6,
                            UserId = 9
                        },
                        new
                        {
                            Id = 18,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5822),
                            Description = "Protective case for 10-inch tablet",
                            IsActive = true,
                            Name = "Tablet Case",
                            Quantity = 10,
                            UserId = 9
                        },
                        new
                        {
                            Id = 19,
                            Category = "Fitness",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5825),
                            Description = "Non-slip yoga mat for workouts",
                            IsActive = true,
                            Name = "Yoga Mat",
                            Quantity = 12,
                            UserId = 10
                        },
                        new
                        {
                            Id = 20,
                            Category = "Fitness",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5828),
                            Description = "Adjustable dumbbells for home workouts",
                            IsActive = true,
                            Name = "Dumbbells Set",
                            Quantity = 3,
                            UserId = 10
                        },
                        new
                        {
                            Id = 21,
                            Category = "Office Supplies",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5831),
                            Description = "Keeps your desk neat and organized",
                            IsActive = true,
                            Name = "Desk Organizer",
                            Quantity = 8,
                            UserId = 11
                        },
                        new
                        {
                            Id = 22,
                            Category = "Office Supplies",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5833),
                            Description = "Set of three notepads",
                            IsActive = true,
                            Name = "Notepad Set",
                            Quantity = 15,
                            UserId = 11
                        },
                        new
                        {
                            Id = 23,
                            Category = "Home Decor",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5836),
                            Description = "Elegant ceramic vase for home decor",
                            IsActive = true,
                            Name = "Ceramic Vase",
                            Quantity = 7,
                            UserId = 12
                        },
                        new
                        {
                            Id = 24,
                            Category = "Home Decor",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5839),
                            Description = "Soft pillow with a decorative cover",
                            IsActive = true,
                            Name = "Decorative Pillow",
                            Quantity = 10,
                            UserId = 12
                        },
                        new
                        {
                            Id = 25,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5841),
                            Description = "High-precision gaming mouse",
                            IsActive = true,
                            Name = "Gaming Mouse",
                            Quantity = 6,
                            UserId = 13
                        },
                        new
                        {
                            Id = 26,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5844),
                            Description = "Tactile mechanical keyboard",
                            IsActive = true,
                            Name = "Mechanical Keyboard",
                            Quantity = 5,
                            UserId = 13
                        },
                        new
                        {
                            Id = 27,
                            Category = "Home Decor",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5847),
                            Description = "Modern abstract wall art",
                            IsActive = true,
                            Name = "Wall Art",
                            Quantity = 4,
                            UserId = 14
                        },
                        new
                        {
                            Id = 28,
                            Category = "Home Decor",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5856),
                            Description = "Stylish table lamp with adjustable brightness",
                            IsActive = true,
                            Name = "Table Lamp",
                            Quantity = 8,
                            UserId = 14
                        },
                        new
                        {
                            Id = 29,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(5859),
                            Description = "Programmable smart thermostat",
                            IsActive = true,
                            Name = "Smart Thermostat",
                            Quantity = 5,
                            UserId = 15
                        },
                        new
                        {
                            Id = 30,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(6047),
                            Description = "Compact air purifier for small rooms",
                            IsActive = true,
                            Name = "Air Purifier",
                            Quantity = 3,
                            UserId = 15
                        },
                        new
                        {
                            Id = 31,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(6051),
                            Description = "Polarized sunglasses with UV protection",
                            IsActive = true,
                            Name = "Sunglasses",
                            Quantity = 10,
                            UserId = 16
                        },
                        new
                        {
                            Id = 32,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(6054),
                            Description = "Classic leather wallet with multiple compartments",
                            IsActive = true,
                            Name = "Leather Wallet",
                            Quantity = 9,
                            UserId = 16
                        },
                        new
                        {
                            Id = 33,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(6057),
                            Description = "Comfortable cotton hoodie",
                            IsActive = true,
                            Name = "Cotton Hoodie",
                            Quantity = 8,
                            UserId = 17
                        },
                        new
                        {
                            Id = 34,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(6060),
                            Description = "Adjustable sports cap",
                            IsActive = true,
                            Name = "Sports Cap",
                            Quantity = 15,
                            UserId = 17
                        },
                        new
                        {
                            Id = 35,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(6063),
                            Description = "Compact charger for mobile devices",
                            IsActive = true,
                            Name = "Portable Charger",
                            Quantity = 14,
                            UserId = 18
                        },
                        new
                        {
                            Id = 36,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(6067),
                            Description = "Set of 3 USB cables",
                            IsActive = true,
                            Name = "USB Cable Set",
                            Quantity = 12,
                            UserId = 18
                        },
                        new
                        {
                            Id = 37,
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(6070),
                            Description = "Non-stick cookware set",
                            IsActive = true,
                            Name = "Cookware Set",
                            Quantity = 6,
                            UserId = 19
                        },
                        new
                        {
                            Id = 38,
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(6073),
                            Description = "Stainless steel knives for every need",
                            IsActive = true,
                            Name = "Knife Set",
                            Quantity = 7,
                            UserId = 19
                        },
                        new
                        {
                            Id = 39,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(6076),
                            Description = "Comfortable everyday pants",
                            IsActive = true,
                            Name = "Pants",
                            Quantity = 6,
                            UserId = 20
                        },
                        new
                        {
                            Id = 40,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2024, 11, 4, 11, 24, 18, 218, DateTimeKind.Local).AddTicks(6079),
                            Description = "Warm sweater for winter",
                            IsActive = true,
                            Name = "Sweater",
                            Quantity = 15,
                            UserId = 20
                        });
                });

            modelBuilder.Entity("monchotradebackend.models.entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            ProductId = 1,
                            Url = "2c2abcc8-d9de-4657-b2ea-9cb6317e35c1.jpg"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 2,
                            Url = "d8440f61-bf9a-45f8-b18c-e9b7e2d35ba8.jpg"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 3,
                            Url = "13268719-b95e-4ffa-af40-83b1c7a7a079.jpg"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 4,
                            Url = "6c97ef84-b64c-4f70-8995-71f8889dd311.png"
                        });
                });

            modelBuilder.Entity("monchotradebackend.models.entities.ProfileImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ProfileImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Url = "64d3f2dd-200a-49d4-b1ac-cb3541ba22f0.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Url = "bae63af5-6084-465d-b4dc-b6549dee41ee.jpg",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("monchotradebackend.models.entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondLastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1990, 5, 15),
                            Country = "Mexico",
                            Email = "ana.martinezgomez@example.com",
                            LastName = "Martinez",
                            Name = "Ana Luisa",
                            PasswordHash = "$2a$11$JkAbOFiMV7HbukMnlUN93uVR7r3X6pT/pAeidM4TTZlaIDe5SgkkW",
                            PhoneNumber = "+52 55 1234 5678",
                            SecondLastName = "Gomez"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1985, 8, 22),
                            Country = "Mexico",
                            Email = "carlos.gomezlopez@example.com",
                            LastName = "Gomez",
                            Name = "Carlos",
                            PasswordHash = "$2a$11$9OD3JJgf7KIicQpUxbEaDu4zuHAV1ibPvunolcqD8r5hx4XBB4HRC",
                            PhoneNumber = "+52 33 9876 5432",
                            SecondLastName = "Lopez"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(1992, 3, 10),
                            Country = "Mexico",
                            Email = "miguel.torresramirez@example.com",
                            LastName = "Torres",
                            Name = "Miguel",
                            PasswordHash = "$2a$11$ilAvzBE/u.WdLhpfCsfYmu4gtIyWf3m.Y69JMuktP91GLhCQYzMR2",
                            PhoneNumber = "+52 81 5555 4444",
                            SecondLastName = "Ramirez"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(1988, 11, 5),
                            Country = "Mexico",
                            Email = "laura.rodriguezfernandez@example.com",
                            LastName = "Rodriguez",
                            Name = "Laura",
                            PasswordHash = "$2a$11$Sq/OKy.RcxfqV1cG2OBinesYYJ3atEc3fTzyv339tuhXg6IKIlu8C",
                            PhoneNumber = "+52 55 2222 3333",
                            SecondLastName = "Fernandez"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(1995, 7, 18),
                            Country = "Mexico",
                            Email = "juan.sanchezmartinez@example.com",
                            LastName = "Sanchez",
                            Name = "Juan Carlos",
                            PasswordHash = "$2a$11$VBAFqGUj0o5SVQMY/on9oepGFzwbmcYyfavu0yWqOARcDc.Xha9Ee",
                            PhoneNumber = "+52 33 7777 8888",
                            SecondLastName = "Martinez"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateOnly(1987, 9, 30),
                            Country = "Mexico",
                            Email = "sofia.ramirezcastillo@example.com",
                            LastName = "Ramirez",
                            Name = "Sofia",
                            PasswordHash = "$2a$11$gw9nn3vgMDUnCN.hp3qWD.RU1cZUcQ5nAVoZVzypgCH0mxeojKbse",
                            PhoneNumber = "+52 81 4444 5555",
                            SecondLastName = "Castillo"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateOnly(1993, 2, 14),
                            Country = "Mexico",
                            Email = "andres.lopezcastro@example.com",
                            LastName = "Lopez",
                            Name = "Andres",
                            PasswordHash = "$2a$11$GRpH/I9pC4KNM3bsOA1qIOgUkdDQOCbZdyU3n6vZcqcGbSmyXBCf.",
                            PhoneNumber = "+52 55 6666 7777",
                            SecondLastName = "Castro"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateOnly(1991, 6, 25),
                            Country = "Mexico",
                            Email = "valentina.castroperez@example.com",
                            LastName = "Castro",
                            Name = "Valentina",
                            PasswordHash = "$2a$11$3z3FmxMUavgzGi8STV8v7uyUOaSq24nBlUZHg8b2LKre1.wJHQ5OS",
                            PhoneNumber = "+52 33 1111 2222",
                            SecondLastName = "Perez"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateOnly(1986, 12, 7),
                            Country = "Mexico",
                            Email = "pedro.jimenezmorales@example.com",
                            LastName = "Jimenez",
                            Name = "Pedro",
                            PasswordHash = "$2a$11$H0XEmhsPNZAEgflxb/mkLuTx1Az2Cl7D/r29o2XPE1iaoHdMLZHMm",
                            PhoneNumber = "+52 81 9999 0000",
                            SecondLastName = "Morales"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateOnly(1994, 4, 12),
                            Country = "Mexico",
                            Email = "mariana.diazherrera@example.com",
                            LastName = "Diaz",
                            Name = "Mariana",
                            PasswordHash = "$2a$11$sl/djQf13eH/xFFCPfhAk.91RkTWtiN9RLJRO7Mw.o1G/eymRCcte",
                            PhoneNumber = "+52 55 3333 4444",
                            SecondLastName = "Herrera"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateOnly(1989, 10, 20),
                            Country = "Mexico",
                            Email = "javier.moralesjimenez@example.com",
                            LastName = "Morales",
                            Name = "Javier",
                            PasswordHash = "$2a$11$Uat/htxSghHKpOt.89OT2.rYOYxUw5SW6jGjMLGkGpkdXQIKNm6lK",
                            PhoneNumber = "+52 33 5555 6666",
                            SecondLastName = "Jimenez"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateOnly(1996, 1, 8),
                            Country = "Mexico",
                            Email = "gabriela.fernandeztorres@example.com",
                            LastName = "Fernandez",
                            Name = "Gabriela",
                            PasswordHash = "$2a$11$Mkzc4WfZ.x7Yu8Ja6466du0M4eddyST9Ykr2RGwMipYaRaKpF914C",
                            PhoneNumber = "+52 81 2222 3333",
                            SecondLastName = "Torres"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateOnly(1984, 8, 16),
                            Country = "Mexico",
                            Email = "tomas.herreramendoza@example.com",
                            LastName = "Herrera",
                            Name = "Tomas",
                            PasswordHash = "$2a$11$HaXBvM9UeurM4LlcR4zSFuysw4FqEJzv6DaWq1iA8YR0GW7tvm0D6",
                            PhoneNumber = "+52 55 7777 8888",
                            SecondLastName = "Mendoza"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateOnly(1997, 5, 3),
                            Country = "Mexico",
                            Email = "natalia.mendozarodriguez@example.com",
                            LastName = "Mendoza",
                            Name = "Natalia",
                            PasswordHash = "$2a$11$pKQF4v5B0pUxHXvBDAjQ0.eU8kdZKc5qwf8BqgJ5SrrmE7uFZpBDi",
                            PhoneNumber = "+52 33 4444 5555",
                            SecondLastName = "Rodriguez"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateOnly(1983, 11, 22),
                            Country = "Mexico",
                            Email = "luis.ruizsanchez@example.com",
                            LastName = "Ruiz",
                            Name = "Luis Fernando",
                            PasswordHash = "$2a$11$9WYa19luuGuv5nAZLJA6y.JD1wwb.uN1AznUcS.woRw2nS8wYoUra",
                            PhoneNumber = "+52 81 6666 7777",
                            SecondLastName = "Sanchez"
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateOnly(1990, 7, 7),
                            Country = "Mexico",
                            Email = "elena.gonzalezreyes@example.com",
                            LastName = "Gonzalez",
                            Name = "Elena",
                            PasswordHash = "$2a$11$0An4Q9tKM22f402sJ/033.vdsbWC00.FB3wd8g7LTJVCkgj210OM6",
                            PhoneNumber = "+52 55 8888 9999",
                            SecondLastName = "Reyes"
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateOnly(1986, 3, 19),
                            Country = "Mexico",
                            Email = "ricardo.reyesgarcia@example.com",
                            LastName = "Reyes",
                            Name = "Ricardo",
                            PasswordHash = "$2a$11$mF4ymiymmsk6ch2aLd/xcukf21JblCAJiwJ19cB2QLsg1.vcwFwXy",
                            PhoneNumber = "+52 33 0000 1111",
                            SecondLastName = "Garcia"
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateOnly(1993, 9, 14),
                            Country = "Mexico",
                            Email = "isabel.garciamoreno@example.com",
                            LastName = "Garcia",
                            Name = "Isabel",
                            PasswordHash = "$2a$11$Ooj7u6GC2DRxrucd7MkMbe5HHeornMihAW85TXHsBRM.SMoCF4r2i",
                            PhoneNumber = "+52 81 3333 4444",
                            SecondLastName = "Moreno"
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateOnly(1988, 6, 30),
                            Country = "Mexico",
                            Email = "daniel.morenosilva@example.com",
                            LastName = "Moreno",
                            Name = "Daniel",
                            PasswordHash = "$2a$11$RJiK4FOPskkLc8RDBkx9oeoB8DDkkhMzNFyf8oSoKsinoPzKhwtl2",
                            PhoneNumber = "+52 55 5555 6666",
                            SecondLastName = "Silva"
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateOnly(1995, 12, 5),
                            Country = "Mexico",
                            Email = "carmen.silvanavarro@example.com",
                            LastName = "Silva",
                            Name = "Carmen",
                            PasswordHash = "$2a$11$Zfeo2WDJ9OQcSTm2uG0KWeY/gwPrEqpS4l5jEeOXbJWQBcfKtXLI.",
                            PhoneNumber = "+52 33 2222 3333",
                            SecondLastName = "Navarro"
                        });
                });

            modelBuilder.Entity("monchotradebackend.models.entities.Product", b =>
                {
                    b.HasOne("monchotradebackend.models.entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("monchotradebackend.models.entities.ProductImage", b =>
                {
                    b.HasOne("monchotradebackend.models.entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("monchotradebackend.models.entities.ProfileImage", b =>
                {
                    b.HasOne("monchotradebackend.models.entities.User", "User")
                        .WithOne("ProfileImage")
                        .HasForeignKey("monchotradebackend.models.entities.ProfileImage", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("monchotradebackend.models.entities.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("monchotradebackend.models.entities.User", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("ProfileImage");
                });
#pragma warning restore 612, 618
        }
    }
}
